Challenge progress card
AgaKhanFoundation/WCF-iOS pull request #166
Opened 2019-07-14 16:53 UTC by mohsinsurani

Rebase completed

2019-08-10 18:35 UTC, compnerd requested changes
Please collapse the changes Into a single commit, this doesn't feel like 13 standalone changes.

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/Challenge.swift
> +    self.navigationController?.navigationBar.barTintColor = #colorLiteral(red: 0.9647058823, green: 0.9725490196, blue: 0.9803921568, alpha: 1.0000000000)
Is the color here not one of the standard colors from the AKF palette?  If so, why not?  If it is, why not use the color constants?

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/Challenge.swift
> +    view.backgroundColor = #colorLiteral(red: 0.9647058823, green: 0.9725490196, blue: 0.9803921568, alpha: 1.0000000000)
Similar

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/Challenge.swift
> +    btnSettings.setImage(UIImage(named: "GearIcon"), for: .normal)
IIRC there is a constant for the name here, please use that.

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/Challenge.swift
> +      $0.right.right.equalToSuperview().inset(Style.Padding.p16)
The button here will have the same constraints as the title label which seems wrong.

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/Challenge.swift
> +    tblCards.backgroundColor = #colorLiteral(red: 0.9647058823, green: 0.9725490196, blue: 0.9803921568, alpha: 1.0000000000)
Similar question about the color as above.

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/Challenge.swift
> +
Why the extra whitespace?

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/Challenge.swift
> +
Why the whitespace?

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/Challenge.swift
> +  private func getTitle(_ title: String, subTitle: String) -> NSMutableAttributedString {
This seems unused, why was this added?

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/Challenge.swift
> +//  func tableView(_ tableView: UITableView,
Please delete the dead code.

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/Challenge.swift
> +        self.arrCards[indexPath.section].expandMile(true)
Why is `expandMile` not a property?  If there is something that needs to occur on the set why not use an observable?  The `didSet` should allow you to post-process the change.

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/Challenge.swift
> +      view.hideFirstLayer(indexPath.row == 1)
Again, an observable property is better I think.

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/Challenge.swift
> +      view.showLastRoundedCorner(indexPath.row == card.miles.count)
Similar

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/JourneyCard.swift
> +//
Please use the header as the rest of the project.

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/JourneyCard.swift
> +//    self.contentView.layer.cornerRadius = Style.Size.s8
Please remove the dead code.

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/JourneyCard.swift
> +
Why the whitespace?

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/JourneyCard.swift
> +      self.layer.maskedCorners = corners// [.layerMinXMinYCorner, .layerMaxXMinYCorner]
Please remove the dead code.

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/JourneyCard.swift
> +typealias StylizedJourneyView =  JourneyCardViewCell & LayoutableCardView
Why do you need a new type alias?  Can you not extend the `StylizedCarView` appropriately?

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/JourneyCardView.swift
> +//
Please use the standard header.

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/JourneyCardView.swift
> +    // TODO(compnerd) figure out the correct size for the image
Did you just copy/paste this code?

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/JourneyMilesCardView.swift
> +//
Header

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/JourneyMilesCardView.swift
> +  var showMileStone: (() -> Void)?
Please give this an explicit accessibility.

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/JourneyMilesCardView.swift
> +      $0.right.equalToSuperview().inset(Style.Padding.p16)
Why not make this the same width as `lblName`?

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/JourneyMilesCardView.swift
> +      $0.right.equalToSuperview().inset(Style.Padding.p8)
Why not make constrain this to have the same right hand side as the `lblName`?

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/JourneyMilesCardView.swift
> +  let viewMileStone: String = "View Milestones"
Can you move these into the Strings table?

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/Challenge/MilestoneDetailCardView.swift
> +//
Standard header please

2019-08-10 18:35 UTC, compnerd commented on WalkingChallenge/LocalizedStrings.swift.orig
> +/**
I think that you added a stray file, please remove it

2019-09-23 04:51 UTC, samisuteria commented
Closing due to stale

2019-09-23 04:51 UTC, closed without merging