Contact selection
AgaKhanFoundation/WCF-iOS pull request #30
Opened 2017-04-05 05:30 UTC by samisuteria

cleans up contact selection and makes it a little simpler 

we should try to fetch all the friends at once instead of async (its very jarring waiting on them to load)

2017-04-05 16:27 UTC, compnerd requested changes
Please rebase the changes, there were some important changes made at the same time.

2017-04-05 16:27 UTC, compnerd commented on WalkingChallenge/Team.swift
> +//    }
Please just kill the dead code.

2017-04-05 16:27 UTC, compnerd commented on WalkingChallenge/ContactPicker.swift
> +    guard let selected = tableView.indexPathsForSelectedRows else { return nil }
This breaks the selection.

2017-04-05 16:27 UTC, compnerd commented on WalkingChallenge/ContactPickerCell.swift
> +      self.picture.image = UIImage(data: data)
This should be on the main thread.  I think you should rebase these changes.

2017-04-05 16:27 UTC, compnerd commented on WalkingChallenge/ContactPickerDataSource.swift
> +    fetchFriends(completion: completion)
Any reason for the extra function?

2017-04-05 16:27 UTC, compnerd commented on WalkingChallenge/ContactPickerDataSource.swift
> +    }
*sigh* I wish there was a more succinct way to write this.

2017-04-05 16:27 UTC, compnerd commented on WalkingChallenge/ContactPickerDataSource.swift
> +    }
Nice!

2017-04-05 16:27 UTC, compnerd commented on WalkingChallenge/ContactPickerDataSource.swift
> +        .filter {$0.first_name.contains(filter) || $0.last_name.contains(filter)}
Why not `$0.display_name.contains(filter)`?  Do we not care about case insensitivity in the search?

2017-04-09 01:59 UTC, samisuteria commented on WalkingChallenge/ContactPickerDataSource.swift
> +    fetchFriends(completion: completion)
just for readability and if we want to do something else in reload later

2017-04-09 02:09 UTC, merged