Fixed back button margin
AgaKhanFoundation/WCF-iOS pull request #332
Opened 2019-10-27 05:00 UTC by faysal-ali

2019-10-28 15:29 UTC, samisuteria requested changes
Minor changes

2019-10-28 15:29 UTC, samisuteria commented on Steps4Impact/App/AppController.swift
> +    // Customizing back button image
Can you customize the navigation controller in the subclass instead of using .apperance `CommonUI/ViewControllers/NavigationController.swift`

2019-10-30 04:01 UTC, faysal-ali commented
@samisuteria I added custom back image but I don't see those images in my commits. I also checked .gitignore and it doesn't ignore it. Do you know what could be happening?

2019-11-05 04:07 UTC, samisuteria commented
required a rebase and merged here: https://github.com/AgaKhanFoundation/WCF-iOS/pull/339

2019-11-05 04:07 UTC, closed without merging