Edit team name
AgaKhanFoundation/WCF-iOS pull request #337
Opened 2019-11-05 00:06 UTC by aabidshamji

Added ability for the team leader to edit the team name

2019-11-05 01:56 UTC, samisuteria commented
/AzurePipelines run

2019-11-05 02:01 UTC, samisuteria commented
/AzurePipelines run

2019-11-05 02:34 UTC, samisuteria requested changes

2019-11-05 02:34 UTC, samisuteria commented on Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTFLLPrioritizer.m
> +/*
why were these files updated?

2019-11-05 02:34 UTC, samisuteria commented on Steps4Impact.xcodeproj/project.pbxproj
> +						DevelopmentTeam = 479QYREFPY;
please don't commit changes to project.pbxproj that effect build settings like dev team or bundle ids

2019-11-05 02:34 UTC, samisuteria commented on Steps4Impact/App/AppController.swift
> +        let loginManager = LoginManager()
this is technically a part of another bug but that's fine - just leave it in the comments of a PR

2019-11-05 02:34 UTC, samisuteria commented on Steps4Impact/Supporting Files/Steps4Impact.entitlements
> -	<key>aps-environment</key>
this shouldn't be deleted

2019-11-05 04:15 UTC, aabidshamji commented on Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTFLLPrioritizer.m
> +/*
Shouldn't have been.

2019-11-05 04:16 UTC, aabidshamji commented
Made necessary changes

2019-11-09 04:31 UTC, samisuteria commented
closing in favor of: https://github.com/AgaKhanFoundation/WCF-iOS/pull/341

2019-11-09 04:31 UTC, closed without merging