Configuration convert to table view
AgaKhanFoundation/WCF-iOS pull request #92
Opened 2017-05-06 20:45 UTC by kforkarim

2017-05-06 23:52 UTC, compnerd requested changes

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/ProfileViewController.swift
> +    let configurationView = SettingsViewController()//ConfigurationViewController()
Why the rename?  Kill the dead code.

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +      make.bottom.equalToSuperview().inset(Style.Padding.p12)
Doesn't this set of constraints make it stretch out vertically?

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +  case device = 0
Is the `= 0` required?

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +  let values: [SettingsnValue]
Typo?  Did you mean `SettingsValue`?

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +struct SettingsnValue {
Same

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +
Unnecessary whitespace.

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +                  values: [SettingsnValue.init(configValue: Strings.Settings.editProfile),SettingsnValue.init(configValue: Strings.Settings.changeEmailAddress),SettingsnValue.init(configValue: String
Indentation is off.  Split at the comma?  It seems pretty long.

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +
Unnecessary whitespace.

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +    } else {
Kill the `else` after the return.

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +      (cell as! PedometerCell).devicePicture.backgroundColor = UIColor.brown
Why not guard it?

    if let cell = cell as? PedometerCell {
      ...
    }

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +    } else {
Kill `else` after the return.

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +  private var configurationTableView: UITableView = UITableView(frame: CGRect.zero, style:UITableViewStyle.grouped)
Missing space after the `:`.

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +    configurationTableView.estimatedRowHeight = 50 //This is an arbitrary number
Space after the comment leader.

2017-05-06 23:52 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +  func loginButtonDidLogOut(_ loginButton: LoginButton) {
Newline before the function please.

2017-07-03 22:31 UTC, kforkarim commented on WalkingChallenge/SettingsViewController.swift
> +  case device = 0
removed 0

2017-07-03 22:32 UTC, kforkarim commented on WalkingChallenge/SettingsViewController.swift
> +  let values: [SettingsnValue]
Fixed the typo.

2017-07-03 22:32 UTC, kforkarim commented on WalkingChallenge/SettingsViewController.swift
> +struct SettingsnValue {
Fixed.

2017-07-03 22:36 UTC, kforkarim commented on WalkingChallenge/SettingsViewController.swift
> +                  values: [SettingsnValue.init(configValue: Strings.Settings.editProfile),SettingsnValue.init(configValue: Strings.Settings.changeEmailAddress),SettingsnValue.init(configValue: String
Fixed.

2017-07-03 22:38 UTC, kforkarim commented on WalkingChallenge/SettingsViewController.swift
> +
Fixed.

2017-07-03 22:40 UTC, kforkarim commented on WalkingChallenge/SettingsViewController.swift
> +    } else {
It's not always the if condition will be satisfied, hence else statement is needed here.

2017-07-03 22:44 UTC, kforkarim commented on WalkingChallenge/SettingsViewController.swift
> +      (cell as! PedometerCell).devicePicture.backgroundColor = UIColor.brown
Fixed.

2017-07-03 22:44 UTC, kforkarim commented on WalkingChallenge/SettingsViewController.swift
> +    } else {
It's not always the if condition will be satisfied, hence else statement is needed here.

2017-07-03 22:45 UTC, kforkarim commented on WalkingChallenge/SettingsViewController.swift
> +  private var configurationTableView: UITableView = UITableView(frame: CGRect.zero, style:UITableViewStyle.grouped)
Fixed.

2017-07-03 22:46 UTC, kforkarim commented on WalkingChallenge/SettingsViewController.swift
> +  func loginButtonDidLogOut(_ loginButton: LoginButton) {
Fixed.

2017-07-03 22:48 UTC, kforkarim commented on WalkingChallenge/SettingsViewController.swift
> +    configurationTableView.estimatedRowHeight = 50 //This is an arbitrary number
Fixed.

2017-07-03 22:49 UTC, kforkarim commented on WalkingChallenge/SettingsViewController.swift
> +      (cell as! PedometerCell).devicePicture.backgroundColor = UIColor.brown
Fixed.

2017-07-03 22:50 UTC, kforkarim commented on WalkingChallenge/ProfileViewController.swift
> +    let configurationView = SettingsViewController()//ConfigurationViewController()
Since ConfigurationViewController needed a lot of changes, I just went ahead and made a new Class. Removed the dead code.

2017-07-04 17:54 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +    } else {
I mean to kill just the `else` keyword.

```
if section == TableSection.device.rawValue {
  return 1
}
let configuration = dataSource?.settingsInfo[section - 1]
return (configuration?.values.count)!
```

I think you can also remove the forced unwrap by doing this:

    return dataSource?.settingsInfo[safe: section - 1]?.values.count ?? 1

2017-07-04 17:56 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +      make.bottom.equalToSuperview().inset(Style.Padding.p12)
Vertical layout issue?

2017-07-04 17:56 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +    ]
Can you indent this please?  Seems like a missing `)` as well.

2017-07-04 17:57 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +                  values: [
Incorrect indentation.  Might be nice to run this through `swift-format`

2017-07-04 17:57 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +                    SettingsInfo(title: Strings.Settings.teams, values: [SettingsValue.init(configValue: Strings.Settings.changeTeams)]),
Wrap at the comma?

2017-07-04 17:58 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +    } else {
I meant literally kill the `else` keyword.

```
if section == TableSection.device.rawValue {
  return 1
}
return dataSource?.settingsInfo[safe: section - 1]?.values.count ?? 1
```

2017-07-04 17:58 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +    return (dataSource?.settingsInfo.count)!+1
Can you rewrite this without the forced unwrap?

2017-07-04 17:59 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +      let justValue = configure?.values[indexPath.row]
Is it okay for configuration to be nil?  If not, change the `let` to a `guard let` perhaps?

2017-07-04 17:59 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +    } else {
See above.

2017-07-04 17:59 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +  private var configurationTableView: UITableView = UITableView(frame: CGRect.zero, style: UITableViewStyle.grouped)
Wrap after the `=`?

2017-07-04 18:00 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +  internal let btnLogout: LoginButton = LoginButton(readPermissions: [])
Shouldn't this match the permissions we want in the login screen?

2017-07-04 18:00 UTC, compnerd commented on WalkingChallenge/SettingsViewController.swift
> +    configurationTableView.tableFooterView = UIView(frame:CGRect(x: 0, y: 0, width: configurationTableView.bounds.size.width, height:50))
Wrap after the `=`?

2019-02-25 20:09 UTC, closed without merging